# Generated by Django 3.2.12 on 2022-02-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='longlat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
